name: Create Release Note

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: build dependencies
        run: pnpm build
      - name: Zip the dist directory
        run: zip -r dist.zip dist
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist.zip
          tag_name: ${{ env.CURRENT_DATETIME }} # Qiitaの記事に合わせて変更
          name: ${{ env.CURRENT_DATETIME }} # Qiitaの記事に合わせて変更
          version: ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.event.pull_request.title }}